services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://kreeda:password@postgres:5432/kreeda_dev
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=${SUPABASE_URL:-https://your-project.supabase.co}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-your-anon-key}
      - JWT_SECRET_KEY=development-secret-key
      - ENVIRONMENT=development
      - DEBUG=true
      - ALLOWED_ORIGINS=["http://localhost:3000", "http://localhost:8080"]
    volumes:
      - ./.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: kreeda_dev
      POSTGRES_USER: kreeda
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kreeda -d kreeda_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
