services:
  # DynamoDB Local for local development
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8001:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Kreeda Backend API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - DYNAMODB_TABLE=kreeda-cricket-data
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-east-1
      - DEBUG=true
      - ENVIRONMENT=development
      - SECRET_KEY=your-development-secret-key-change-in-production
      - USE_COGNITO=false
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    depends_on:
      dynamodb-local:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and WebSocket management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
