"""Initial cricket models

Revision ID: 001_initial
Revises: 
Create Date: 2025-09-26 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create teams table
    op.create_table('teams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('short_name', sa.String(length=10), nullable=False),
        sa.Column('logo_url', sa.String(length=500), nullable=True),
        sa.Column('home_ground', sa.String(length=200), nullable=True),
        sa.Column('captain_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    
    # Create players table
    op.create_table('players',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=True),
        sa.Column('jersey_number', sa.Integer(), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('batting_style', sa.String(length=50), nullable=True),
        sa.Column('bowling_style', sa.String(length=50), nullable=True),
        sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    
    # Add foreign key for team captain
    op.create_foreign_key('fk_teams_captain_id', 'teams', 'players', ['captain_id'], ['id'])
    
    # Create matches table
    op.create_table('matches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('match_format', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), default='SCHEDULED'),
        sa.Column('home_team_id', sa.Integer(), nullable=False),
        sa.Column('away_team_id', sa.Integer(), nullable=False),
        sa.Column('venue', sa.String(length=200), nullable=True),
        sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('overs_per_innings', sa.Integer(), default=20),
        sa.Column('balls_per_over', sa.Integer(), default=6),
        sa.Column('max_wickets', sa.Integer(), default=10),
        sa.Column('toss_winner_id', sa.Integer(), nullable=True),
        sa.Column('toss_decision', sa.String(length=10), nullable=True),
        sa.Column('winner_id', sa.Integer(), nullable=True),
        sa.Column('result_type', sa.String(length=50), nullable=True),
        sa.Column('margin', sa.Integer(), nullable=True),
        sa.Column('dual_scorer_required', sa.Boolean(), default=True),
        sa.Column('primary_scorer_id', sa.String(length=100), nullable=True),
        sa.Column('secondary_scorer_id', sa.String(length=100), nullable=True),
        sa.Column('weather_conditions', sa.String(length=200), nullable=True),
        sa.Column('pitch_conditions', sa.String(length=200), nullable=True),
        sa.Column('match_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('home_team_id != away_team_id', name='different_teams'),
        sa.CheckConstraint('overs_per_innings > 0', name='positive_overs'),
        sa.CheckConstraint('balls_per_over > 0', name='positive_balls_per_over'),
        sa.CheckConstraint('max_wickets > 0', name='positive_max_wickets'),
        sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    
    # Create innings table
    op.create_table('innings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('innings_number', sa.Integer(), nullable=False),
        sa.Column('batting_team_id', sa.Integer(), nullable=False),
        sa.Column('bowling_team_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), default='NOT_STARTED'),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('total_runs', sa.Integer(), default=0),
        sa.Column('total_wickets', sa.Integer(), default=0),
        sa.Column('total_overs', sa.Numeric(precision=4, scale=1), default=0.0),
        sa.Column('total_balls', sa.Integer(), default=0),
        sa.Column('wides', sa.Integer(), default=0),
        sa.Column('no_balls', sa.Integer(), default=0),
        sa.Column('byes', sa.Integer(), default=0),
        sa.Column('leg_byes', sa.Integer(), default=0),
        sa.Column('penalties', sa.Integer(), default=0),
        sa.Column('target_runs', sa.Integer(), nullable=True),
        sa.Column('is_declared', sa.Boolean(), default=False),
        sa.Column('is_forfeited', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('total_runs >= 0', name='non_negative_runs'),
        sa.CheckConstraint('total_wickets >= 0', name='non_negative_wickets'),
        sa.CheckConstraint('total_overs >= 0', name='non_negative_overs'),
        sa.CheckConstraint('innings_number > 0', name='positive_innings_number'),
        sa.ForeignKeyConstraint(['batting_team_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['bowling_team_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('match_id', 'innings_number', name='unique_innings_per_match')
    )
    op.create_index(op.f('ix_innings_id'), 'innings', ['id'], unique=False)
    
    # Create overs table
    op.create_table('overs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('innings_id', sa.Integer(), nullable=False),
        sa.Column('over_number', sa.Integer(), nullable=False),
        sa.Column('bowler_id', sa.Integer(), nullable=False),
        sa.Column('runs_conceded', sa.Integer(), default=0),
        sa.Column('wickets_taken', sa.Integer(), default=0),
        sa.Column('balls_bowled', sa.Integer(), default=0),
        sa.Column('legal_balls', sa.Integer(), default=0),
        sa.Column('wides', sa.Integer(), default=0),
        sa.Column('no_balls', sa.Integer(), default=0),
        sa.Column('byes', sa.Integer(), default=0),
        sa.Column('leg_byes', sa.Integer(), default=0),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('over_number > 0', name='positive_over_number'),
        sa.CheckConstraint('runs_conceded >= 0', name='non_negative_runs_conceded'),
        sa.CheckConstraint('wickets_taken >= 0', name='non_negative_wickets_taken'),
        sa.CheckConstraint('balls_bowled >= 0', name='non_negative_balls_bowled'),
        sa.CheckConstraint('legal_balls >= 0', name='non_negative_legal_balls'),
        sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ),
        sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('innings_id', 'over_number', name='unique_over_per_innings')
    )
    op.create_index(op.f('ix_overs_id'), 'overs', ['id'], unique=False)
    
    # Create balls table
    op.create_table('balls',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('over_id', sa.Integer(), nullable=False),
        sa.Column('ball_number', sa.Integer(), nullable=False),
        sa.Column('bowler_id', sa.Integer(), nullable=False),
        sa.Column('batsman_id', sa.Integer(), nullable=False),
        sa.Column('non_striker_id', sa.Integer(), nullable=False),
        sa.Column('runs_scored', sa.Integer(), default=0),
        sa.Column('is_boundary', sa.Boolean(), default=False),
        sa.Column('boundary_type', sa.Integer(), nullable=True),
        sa.Column('extra_type', sa.String(length=20), nullable=True),
        sa.Column('extra_runs', sa.Integer(), default=0),
        sa.Column('is_legal_delivery', sa.Boolean(), default=True),
        sa.Column('is_wicket', sa.Boolean(), default=False),
        sa.Column('dismissal_type', sa.String(length=30), nullable=True),
        sa.Column('dismissed_player_id', sa.Integer(), nullable=True),
        sa.Column('fielder_id', sa.Integer(), nullable=True),
        sa.Column('ball_speed', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('ball_type', sa.String(length=50), nullable=True),
        sa.Column('primary_scorer_confirmed', sa.Boolean(), default=False),
        sa.Column('secondary_scorer_confirmed', sa.Boolean(), default=False),
        sa.Column('has_dispute', sa.Boolean(), default=False),
        sa.Column('dispute_resolved', sa.Boolean(), default=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('runs_scored >= 0', name='non_negative_runs_scored'),
        sa.CheckConstraint('extra_runs >= 0', name='non_negative_extra_runs'),
        sa.CheckConstraint('ball_number > 0', name='positive_ball_number'),
        sa.CheckConstraint(
            '(is_wicket = false AND dismissal_type IS NULL AND dismissed_player_id IS NULL) OR '
            '(is_wicket = true AND dismissal_type IS NOT NULL)',
            name='consistent_wicket_info'
        ),
        sa.CheckConstraint(
            '(is_boundary = false AND boundary_type IS NULL) OR '
            '(is_boundary = true AND boundary_type IN (4, 6))',
            name='consistent_boundary_info'
        ),
        sa.ForeignKeyConstraint(['batsman_id'], ['players.id'], ),
        sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ),
        sa.ForeignKeyConstraint(['dismissed_player_id'], ['players.id'], ),
        sa.ForeignKeyConstraint(['fielder_id'], ['players.id'], ),
        sa.ForeignKeyConstraint(['non_striker_id'], ['players.id'], ),
        sa.ForeignKeyConstraint(['over_id'], ['overs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balls_id'), 'balls', ['id'], unique=False)
    
    # Create batting_performances table
    op.create_table('batting_performances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('innings_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('runs_scored', sa.Integer(), default=0),
        sa.Column('balls_faced', sa.Integer(), default=0),
        sa.Column('fours', sa.Integer(), default=0),
        sa.Column('sixes', sa.Integer(), default=0),
        sa.Column('is_out', sa.Boolean(), default=False),
        sa.Column('dismissal_type', sa.String(length=30), nullable=True),
        sa.Column('bowler_id', sa.Integer(), nullable=True),
        sa.Column('fielder_id', sa.Integer(), nullable=True),
        sa.Column('batting_position', sa.Integer(), nullable=False),
        sa.Column('came_in_at_over', sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column('went_out_at_over', sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('runs_scored >= 0', name='non_negative_runs_scored'),
        sa.CheckConstraint('balls_faced >= 0', name='non_negative_balls_faced'),
        sa.CheckConstraint('fours >= 0', name='non_negative_fours'),
        sa.CheckConstraint('sixes >= 0', name='non_negative_sixes'),
        sa.CheckConstraint('batting_position > 0', name='positive_batting_position'),
        sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ),
        sa.ForeignKeyConstraint(['fielder_id'], ['players.id'], ),
        sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('innings_id', 'player_id', name='unique_batting_performance'),
        sa.UniqueConstraint('innings_id', 'batting_position', name='unique_batting_position')
    )
    op.create_index(op.f('ix_batting_performances_id'), 'batting_performances', ['id'], unique=False)
    
    # Create bowling_performances table
    op.create_table('bowling_performances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('innings_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('overs_bowled', sa.Numeric(precision=4, scale=1), default=0.0),
        sa.Column('runs_conceded', sa.Integer(), default=0),
        sa.Column('wickets_taken', sa.Integer(), default=0),
        sa.Column('maidens', sa.Integer(), default=0),
        sa.Column('wides', sa.Integer(), default=0),
        sa.Column('no_balls', sa.Integer(), default=0),
        sa.Column('dots', sa.Integer(), default=0),
        sa.Column('boundaries_conceded', sa.Integer(), default=0),
        sa.Column('sixes_conceded', sa.Integer(), default=0),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('overs_bowled >= 0', name='non_negative_overs_bowled'),
        sa.CheckConstraint('runs_conceded >= 0', name='non_negative_runs_conceded'),
        sa.CheckConstraint('wickets_taken >= 0', name='non_negative_wickets_taken'),
        sa.CheckConstraint('maidens >= 0', name='non_negative_maidens'),
        sa.CheckConstraint('wides >= 0', name='non_negative_wides'),
        sa.CheckConstraint('no_balls >= 0', name='non_negative_no_balls'),
        sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('innings_id', 'player_id', name='unique_bowling_performance')
    )
    op.create_index(op.f('ix_bowling_performances_id'), 'bowling_performances', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bowling_performances')
    op.drop_table('batting_performances')
    op.drop_table('balls')
    op.drop_table('overs')
    op.drop_table('innings')
    op.drop_table('matches')
    op.drop_table('players')
    op.drop_table('teams')
    # ### end Alembic commands ###