"""Add tournament system models

Revision ID: 29c563fd012d
Revises: 8a48ed4caad4
Create Date: 2025-09-19 00:02:02.683169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c563fd012d'
down_revision: Union[str, None] = '8a48ed4caad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cricket_balls_match_innings', table_name='cricket_balls')
    op.drop_index('idx_cricket_balls_over', table_name='cricket_balls')
    op.drop_index('idx_cricket_matches_date', table_name='cricket_matches')
    op.drop_index('idx_cricket_matches_status', table_name='cricket_matches')
    op.drop_index('idx_cricket_matches_teams', table_name='cricket_matches')
    op.drop_index('idx_playing_xi_batting_order', table_name='match_playing_xi')
    op.drop_index('idx_playing_xi_match_team', table_name='match_playing_xi')
    op.drop_index('idx_team_invitations_expires', table_name='team_invitations')
    op.drop_index('idx_team_invitations_team_status', table_name='team_invitations')
    op.drop_index('idx_team_members_lookup', table_name='team_members')
    op.drop_index('idx_team_members_user', table_name='team_members')
    op.drop_index('idx_teams_active', table_name='teams')
    op.drop_index('idx_users_email_active', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_teams_active', 'teams', ['is_active'], unique=False)
    op.create_index('idx_team_members_user', 'team_members', ['user_id'], unique=False)
    op.create_index('idx_team_members_lookup', 'team_members', ['team_id', 'user_id'], unique=False)
    op.create_index('idx_team_invitations_team_status', 'team_invitations', ['team_id', 'status'], unique=False)
    op.create_index('idx_team_invitations_expires', 'team_invitations', ['expires_at'], unique=False)
    op.create_index('idx_playing_xi_match_team', 'match_playing_xi', ['match_id', 'team_id'], unique=False)
    op.create_index('idx_playing_xi_batting_order', 'match_playing_xi', ['match_id', 'team_id', 'batting_order'], unique=False)
    op.create_index('idx_cricket_matches_teams', 'cricket_matches', ['team_a_id', 'team_b_id'], unique=False)
    op.create_index('idx_cricket_matches_status', 'cricket_matches', ['status'], unique=False)
    op.create_index('idx_cricket_matches_date', 'cricket_matches', ['match_date'], unique=False)
    op.create_index('idx_cricket_balls_over', 'cricket_balls', ['match_id', 'over_number', 'ball_number'], unique=False)
    op.create_index('idx_cricket_balls_match_innings', 'cricket_balls', ['match_id', 'innings'], unique=False)
    # ### end Alembic commands ###
