"""Add modular user, team, and cricket systems final

Revision ID: 570e33725d31
Revises: 001_initial
Create Date: 2025-09-27 05:42:03.530695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '570e33725d31'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cricket_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('home_ground', sa.String(length=200), nullable=True),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cricket_teams_id'), 'cricket_teams', ['id'], unique=False)
    op.create_index(op.f('ix_cricket_teams_name'), 'cricket_teams', ['name'], unique=False)
    op.create_table('sport_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sport_type', sa.String(length=50), nullable=False),
    sa.Column('skill_level', sa.String(length=20), nullable=False),
    sa.Column('primary_position', sa.String(length=50), nullable=True),
    sa.Column('secondary_positions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('playing_style', sa.String(length=100), nullable=True),
    sa.Column('career_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("skill_level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'PROFESSIONAL')", name='valid_skill_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_profiles_id'), 'sport_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_sport_profiles_sport_type'), 'sport_profiles', ['sport_type'], unique=False)
    op.create_index(op.f('ix_sport_profiles_user_id'), 'sport_profiles', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("phone_number ~ '^\\+?[1-9]\\d{1,14}$'", name='valid_phone'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_full_name'), 'user_profiles', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_profiles_location'), 'user_profiles', ['location'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_teams',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('home_ground', sa.String(length=200), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('auto_accept_members', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("status IN ('active', 'inactive', 'disbanded', 'pending')", name='valid_team_status'),
    sa.CheckConstraint("team_type IN ('cricket', 'football', 'basketball', 'hockey', 'volleyball', 'badminton', 'tennis')", name='valid_team_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'team_type', 'city', name='uq_team_name_type_city')
    )
    op.create_index('ix_teams_location', 'user_teams', ['city', 'state'], unique=False)
    op.create_index('ix_teams_name_type', 'user_teams', ['name', 'team_type'], unique=False)
    op.create_index(op.f('ix_user_teams_city'), 'user_teams', ['city'], unique=False)
    op.create_index(op.f('ix_user_teams_id'), 'user_teams', ['id'], unique=False)
    op.create_index(op.f('ix_user_teams_is_public'), 'user_teams', ['is_public'], unique=False)
    op.create_index(op.f('ix_user_teams_name'), 'user_teams', ['name'], unique=False)
    op.create_index(op.f('ix_user_teams_status'), 'user_teams', ['status'], unique=False)
    op.create_index(op.f('ix_user_teams_team_type'), 'user_teams', ['team_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supabase_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='valid_email'),
    sa.CheckConstraint('LENGTH(username) >= 3', name='username_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cricket_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('match_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overs_per_innings', sa.Integer(), nullable=False),
    sa.Column('balls_per_over', sa.Integer(), nullable=False),
    sa.Column('max_wickets', sa.Integer(), nullable=False),
    sa.Column('toss_winner_id', sa.Integer(), nullable=True),
    sa.Column('toss_decision', sa.String(length=10), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=50), nullable=True),
    sa.Column('margin', sa.Integer(), nullable=True),
    sa.Column('dual_scorer_required', sa.Boolean(), nullable=False),
    sa.Column('primary_scorer_id', sa.String(length=100), nullable=True),
    sa.Column('secondary_scorer_id', sa.String(length=100), nullable=True),
    sa.Column('weather_conditions', sa.String(length=200), nullable=True),
    sa.Column('pitch_conditions', sa.String(length=200), nullable=True),
    sa.Column('match_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('balls_per_over > 0', name='cricket_positive_balls_per_over'),
    sa.CheckConstraint('home_team_id != away_team_id', name='cricket_different_teams'),
    sa.CheckConstraint('max_wickets > 0', name='cricket_positive_max_wickets'),
    sa.CheckConstraint('overs_per_innings > 0', name='cricket_positive_overs'),
    sa.ForeignKeyConstraint(['away_team_id'], ['cricket_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['cricket_teams.id'], ),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['cricket_teams.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['cricket_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cricket_matches_id'), 'cricket_matches', ['id'], unique=False)
    op.create_table('cricket_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('batting_style', sa.String(length=50), nullable=True),
    sa.Column('bowling_style', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['team_id'], ['cricket_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cricket_players_id'), 'cricket_players', ['id'], unique=False)
    op.create_index(op.f('ix_cricket_players_name'), 'cricket_players', ['name'], unique=False)
    op.create_table('team_invitations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invited_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('invited_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('proposed_role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("proposed_role IN ('captain', 'vice_captain', 'player', 'coach', 'manager', 'admin')", name='valid_proposed_role'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'expired')", name='valid_invitation_status'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['user_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invitations_id'), 'team_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_team_invitations_invited_by_id'), 'team_invitations', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_invited_user_id'), 'team_invitations', ['invited_user_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_status'), 'team_invitations', ['status'], unique=False)
    op.create_index('ix_team_invitations_status_expires', 'team_invitations', ['status', 'expires_at'], unique=False)
    op.create_index('ix_team_invitations_team_email', 'team_invitations', ['team_id', 'email'], unique=False)
    op.create_index(op.f('ix_team_invitations_team_id'), 'team_invitations', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('joined_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("role IN ('captain', 'vice_captain', 'player', 'coach', 'manager', 'admin')", name='valid_member_role'),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended', 'pending', 'left')", name='valid_member_status'),
    sa.ForeignKeyConstraint(['team_id'], ['user_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'jersey_number', name='uq_team_jersey'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_user')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_role'), 'team_members', ['role'], unique=False)
    op.create_index('ix_team_members_status', 'team_members', ['status'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index('ix_team_members_team_role', 'team_members', ['team_id', 'role'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('cricket_innings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.Column('batting_team_id', sa.Integer(), nullable=False),
    sa.Column('bowling_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_wickets', sa.Integer(), nullable=False),
    sa.Column('total_overs', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('total_balls', sa.Integer(), nullable=False),
    sa.Column('wides', sa.Integer(), nullable=False),
    sa.Column('no_balls', sa.Integer(), nullable=False),
    sa.Column('byes', sa.Integer(), nullable=False),
    sa.Column('leg_byes', sa.Integer(), nullable=False),
    sa.Column('penalties', sa.Integer(), nullable=False),
    sa.Column('target_runs', sa.Integer(), nullable=True),
    sa.Column('is_declared', sa.Boolean(), nullable=False),
    sa.Column('is_forfeited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('innings_number > 0', name='cricket_positive_innings_number'),
    sa.CheckConstraint('total_overs >= 0', name='cricket_non_negative_overs'),
    sa.CheckConstraint('total_runs >= 0', name='cricket_non_negative_runs'),
    sa.CheckConstraint('total_wickets >= 0', name='cricket_non_negative_wickets'),
    sa.ForeignKeyConstraint(['batting_team_id'], ['cricket_teams.id'], ),
    sa.ForeignKeyConstraint(['bowling_team_id'], ['cricket_teams.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['cricket_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'innings_number', name='unique_cricket_innings_per_match')
    )
    op.create_index(op.f('ix_cricket_innings_id'), 'cricket_innings', ['id'], unique=False)
    op.create_table('cricket_batting_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('innings_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('balls_faced', sa.Integer(), nullable=False),
    sa.Column('fours', sa.Integer(), nullable=False),
    sa.Column('sixes', sa.Integer(), nullable=False),
    sa.Column('is_out', sa.Boolean(), nullable=False),
    sa.Column('dismissal_type', sa.String(length=30), nullable=True),
    sa.Column('bowler_id', sa.Integer(), nullable=True),
    sa.Column('fielder_id', sa.Integer(), nullable=True),
    sa.Column('batting_position', sa.Integer(), nullable=False),
    sa.Column('came_in_at_over', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('went_out_at_over', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('balls_faced >= 0', name='non_negative_balls_faced'),
    sa.CheckConstraint('batting_position > 0', name='positive_batting_position'),
    sa.CheckConstraint('fours >= 0', name='non_negative_fours'),
    sa.CheckConstraint('runs_scored >= 0', name='non_negative_runs_scored'),
    sa.CheckConstraint('sixes >= 0', name='non_negative_sixes'),
    sa.ForeignKeyConstraint(['bowler_id'], ['cricket_players.id'], ),
    sa.ForeignKeyConstraint(['fielder_id'], ['cricket_players.id'], ),
    sa.ForeignKeyConstraint(['innings_id'], ['cricket_innings.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['cricket_players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('innings_id', 'batting_position', name='unique_batting_position'),
    sa.UniqueConstraint('innings_id', 'player_id', name='cricket_unique_batting_performance')
    )
    op.create_index(op.f('ix_cricket_batting_performances_id'), 'cricket_batting_performances', ['id'], unique=False)
    op.create_table('cricket_bowling_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('innings_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('overs_bowled', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('runs_conceded', sa.Integer(), nullable=False),
    sa.Column('wickets_taken', sa.Integer(), nullable=False),
    sa.Column('maidens', sa.Integer(), nullable=False),
    sa.Column('wides', sa.Integer(), nullable=False),
    sa.Column('no_balls', sa.Integer(), nullable=False),
    sa.Column('dots', sa.Integer(), nullable=False),
    sa.Column('boundaries_conceded', sa.Integer(), nullable=False),
    sa.Column('sixes_conceded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('maidens >= 0', name='non_negative_maidens'),
    sa.CheckConstraint('no_balls >= 0', name='non_negative_no_balls'),
    sa.CheckConstraint('overs_bowled >= 0', name='non_negative_overs_bowled'),
    sa.CheckConstraint('runs_conceded >= 0', name='non_negative_runs_conceded'),
    sa.CheckConstraint('wickets_taken >= 0', name='non_negative_wickets_taken'),
    sa.CheckConstraint('wides >= 0', name='non_negative_wides'),
    sa.ForeignKeyConstraint(['innings_id'], ['cricket_innings.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['cricket_players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('innings_id', 'player_id', name='unique_bowling_performance')
    )
    op.create_index(op.f('ix_cricket_bowling_performances_id'), 'cricket_bowling_performances', ['id'], unique=False)
    op.create_table('cricket_overs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('innings_id', sa.Integer(), nullable=False),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('runs_conceded', sa.Integer(), nullable=False),
    sa.Column('wickets_taken', sa.Integer(), nullable=False),
    sa.Column('balls_bowled', sa.Integer(), nullable=False),
    sa.Column('legal_balls', sa.Integer(), nullable=False),
    sa.Column('wides', sa.Integer(), nullable=False),
    sa.Column('no_balls', sa.Integer(), nullable=False),
    sa.Column('byes', sa.Integer(), nullable=False),
    sa.Column('leg_byes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('balls_bowled >= 0', name='cricket_non_negative_balls_bowled'),
    sa.CheckConstraint('legal_balls >= 0', name='cricket_non_negative_legal_balls'),
    sa.CheckConstraint('over_number > 0', name='cricket_positive_over_number'),
    sa.CheckConstraint('runs_conceded >= 0', name='non_negative_runs_conceded'),
    sa.CheckConstraint('wickets_taken >= 0', name='non_negative_wickets_taken'),
    sa.ForeignKeyConstraint(['bowler_id'], ['cricket_players.id'], ),
    sa.ForeignKeyConstraint(['innings_id'], ['cricket_innings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('innings_id', 'over_number', name='cricket_unique_over_per_innings')
    )
    op.create_index(op.f('ix_cricket_overs_id'), 'cricket_overs', ['id'], unique=False)
    op.create_table('cricket_balls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('over_id', sa.Integer(), nullable=False),
    sa.Column('ball_number', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('batsman_id', sa.Integer(), nullable=False),
    sa.Column('non_striker_id', sa.Integer(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('is_boundary', sa.Boolean(), nullable=False),
    sa.Column('boundary_type', sa.Integer(), nullable=True),
    sa.Column('extra_type', sa.String(length=20), nullable=True),
    sa.Column('extra_runs', sa.Integer(), nullable=False),
    sa.Column('is_legal_delivery', sa.Boolean(), nullable=False),
    sa.Column('is_wicket', sa.Boolean(), nullable=False),
    sa.Column('dismissal_type', sa.String(length=30), nullable=True),
    sa.Column('dismissed_player_id', sa.Integer(), nullable=True),
    sa.Column('fielder_id', sa.Integer(), nullable=True),
    sa.Column('ball_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ball_type', sa.String(length=50), nullable=True),
    sa.Column('primary_scorer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('secondary_scorer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('has_dispute', sa.Boolean(), nullable=False),
    sa.Column('dispute_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint('(is_boundary = false AND boundary_type IS NULL) OR (is_boundary = true AND boundary_type IN (4, 6))', name='cricket_consistent_boundary_info'),
    sa.CheckConstraint('(is_wicket = false AND dismissal_type IS NULL AND dismissed_player_id IS NULL) OR (is_wicket = true AND dismissal_type IS NOT NULL)', name='cricket_consistent_wicket_info'),
    sa.CheckConstraint('ball_number > 0', name='cricket_positive_ball_number'),
    sa.CheckConstraint('extra_runs >= 0', name='cricket_non_negative_extra_runs'),
    sa.CheckConstraint('runs_scored >= 0', name='non_negative_runs_scored'),
    sa.ForeignKeyConstraint(['batsman_id'], ['cricket_players.id'], ),
    sa.ForeignKeyConstraint(['bowler_id'], ['cricket_players.id'], ),
    sa.ForeignKeyConstraint(['dismissed_player_id'], ['cricket_players.id'], ),
    sa.ForeignKeyConstraint(['fielder_id'], ['cricket_players.id'], ),
    sa.ForeignKeyConstraint(['non_striker_id'], ['cricket_players.id'], ),
    sa.ForeignKeyConstraint(['over_id'], ['cricket_overs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cricket_balls_id'), 'cricket_balls', ['id'], unique=False)
    op.drop_index('ix_batting_performances_id', table_name='batting_performances')
    op.drop_table('batting_performances')
    op.drop_index('ix_innings_id', table_name='innings')
    op.drop_table('innings')
    op.drop_index('ix_bowling_performances_id', table_name='bowling_performances')
    op.drop_table('bowling_performances')
    op.drop_index('ix_balls_id', table_name='balls')
    op.drop_table('balls')
    op.drop_index('ix_matches_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_overs_id', table_name='overs')
    op.drop_table('overs')
    op.drop_index('ix_players_id', table_name='players')
    op.drop_index('ix_players_name', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_teams_id', table_name='teams')
    op.drop_index('ix_teams_name', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teams_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('home_ground', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('captain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], name='fk_teams_captain_id'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.create_index('ix_teams_id', 'teams', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('players_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jersey_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('batting_style', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bowling_style', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='players_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='players_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_players_name', 'players', ['name'], unique=False)
    op.create_index('ix_players_id', 'players', ['id'], unique=False)
    op.create_table('overs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('overs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('innings_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('over_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bowler_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('runs_conceded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wickets_taken', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balls_bowled', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('legal_balls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_balls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('byes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('leg_byes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('balls_bowled >= 0', name='non_negative_balls_bowled'),
    sa.CheckConstraint('legal_balls >= 0', name='non_negative_legal_balls'),
    sa.CheckConstraint('over_number > 0', name='positive_over_number'),
    sa.CheckConstraint('runs_conceded >= 0', name='non_negative_runs_conceded'),
    sa.CheckConstraint('wickets_taken >= 0', name='non_negative_wickets_taken'),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], name='overs_bowler_id_fkey'),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], name='overs_innings_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='overs_pkey'),
    sa.UniqueConstraint('innings_id', 'over_number', name='unique_over_per_innings'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_overs_id', 'overs', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('matches_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('match_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('scheduled_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actual_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('actual_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('overs_per_innings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balls_per_over', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_wickets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toss_winner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toss_decision', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('winner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('margin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dual_scorer_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('primary_scorer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('secondary_scorer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('weather_conditions', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pitch_conditions', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('match_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('balls_per_over > 0', name='positive_balls_per_over'),
    sa.CheckConstraint('home_team_id <> away_team_id', name='different_teams'),
    sa.CheckConstraint('max_wickets > 0', name='positive_max_wickets'),
    sa.CheckConstraint('overs_per_innings > 0', name='positive_overs'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name='matches_away_team_id_fkey'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name='matches_home_team_id_fkey'),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.id'], name='matches_toss_winner_id_fkey'),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], name='matches_winner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='matches_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_matches_id', 'matches', ['id'], unique=False)
    op.create_table('balls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('over_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ball_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bowler_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batsman_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('non_striker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('runs_scored', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_boundary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('boundary_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extra_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('extra_runs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_legal_delivery', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_wicket', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dismissal_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('dismissed_player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fielder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_speed', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('ball_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('primary_scorer_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('secondary_scorer_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_dispute', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dispute_resolved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('ball_number > 0', name='positive_ball_number'),
    sa.CheckConstraint('extra_runs >= 0', name='non_negative_extra_runs'),
    sa.CheckConstraint('is_boundary = false AND boundary_type IS NULL OR is_boundary = true AND (boundary_type = ANY (ARRAY[4, 6]))', name='consistent_boundary_info'),
    sa.CheckConstraint('is_wicket = false AND dismissal_type IS NULL AND dismissed_player_id IS NULL OR is_wicket = true AND dismissal_type IS NOT NULL', name='consistent_wicket_info'),
    sa.CheckConstraint('runs_scored >= 0', name='non_negative_runs_scored'),
    sa.ForeignKeyConstraint(['batsman_id'], ['players.id'], name='balls_batsman_id_fkey'),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], name='balls_bowler_id_fkey'),
    sa.ForeignKeyConstraint(['dismissed_player_id'], ['players.id'], name='balls_dismissed_player_id_fkey'),
    sa.ForeignKeyConstraint(['fielder_id'], ['players.id'], name='balls_fielder_id_fkey'),
    sa.ForeignKeyConstraint(['non_striker_id'], ['players.id'], name='balls_non_striker_id_fkey'),
    sa.ForeignKeyConstraint(['over_id'], ['overs.id'], name='balls_over_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='balls_pkey')
    )
    op.create_index('ix_balls_id', 'balls', ['id'], unique=False)
    op.create_table('bowling_performances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('innings_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overs_bowled', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('runs_conceded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wickets_taken', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maidens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_balls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('boundaries_conceded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sixes_conceded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('maidens >= 0', name='non_negative_maidens'),
    sa.CheckConstraint('no_balls >= 0', name='non_negative_no_balls'),
    sa.CheckConstraint('overs_bowled >= 0::numeric', name='non_negative_overs_bowled'),
    sa.CheckConstraint('runs_conceded >= 0', name='non_negative_runs_conceded'),
    sa.CheckConstraint('wickets_taken >= 0', name='non_negative_wickets_taken'),
    sa.CheckConstraint('wides >= 0', name='non_negative_wides'),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], name='bowling_performances_innings_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='bowling_performances_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bowling_performances_pkey'),
    sa.UniqueConstraint('innings_id', 'player_id', name='unique_bowling_performance')
    )
    op.create_index('ix_bowling_performances_id', 'bowling_performances', ['id'], unique=False)
    op.create_table('innings',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('innings_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('innings_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batting_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bowling_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_runs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_wickets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_overs', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('total_balls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wides', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_balls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('byes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('leg_byes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalties', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_runs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_declared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_forfeited', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('innings_number > 0', name='positive_innings_number'),
    sa.CheckConstraint('total_overs >= 0::numeric', name='non_negative_overs'),
    sa.CheckConstraint('total_runs >= 0', name='non_negative_runs'),
    sa.CheckConstraint('total_wickets >= 0', name='non_negative_wickets'),
    sa.ForeignKeyConstraint(['batting_team_id'], ['teams.id'], name='innings_batting_team_id_fkey'),
    sa.ForeignKeyConstraint(['bowling_team_id'], ['teams.id'], name='innings_bowling_team_id_fkey'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='innings_match_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='innings_pkey'),
    sa.UniqueConstraint('match_id', 'innings_number', name='unique_innings_per_match'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_innings_id', 'innings', ['id'], unique=False)
    op.create_table('batting_performances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('innings_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('runs_scored', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balls_faced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sixes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_out', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dismissal_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('bowler_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fielder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batting_position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('came_in_at_over', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('went_out_at_over', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('balls_faced >= 0', name='non_negative_balls_faced'),
    sa.CheckConstraint('batting_position > 0', name='positive_batting_position'),
    sa.CheckConstraint('fours >= 0', name='non_negative_fours'),
    sa.CheckConstraint('runs_scored >= 0', name='non_negative_runs_scored'),
    sa.CheckConstraint('sixes >= 0', name='non_negative_sixes'),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], name='batting_performances_bowler_id_fkey'),
    sa.ForeignKeyConstraint(['fielder_id'], ['players.id'], name='batting_performances_fielder_id_fkey'),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], name='batting_performances_innings_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='batting_performances_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='batting_performances_pkey'),
    sa.UniqueConstraint('innings_id', 'batting_position', name='unique_batting_position'),
    sa.UniqueConstraint('innings_id', 'player_id', name='unique_batting_performance')
    )
    op.create_index('ix_batting_performances_id', 'batting_performances', ['id'], unique=False)
    op.drop_index(op.f('ix_cricket_balls_id'), table_name='cricket_balls')
    op.drop_table('cricket_balls')
    op.drop_index(op.f('ix_cricket_overs_id'), table_name='cricket_overs')
    op.drop_table('cricket_overs')
    op.drop_index(op.f('ix_cricket_bowling_performances_id'), table_name='cricket_bowling_performances')
    op.drop_table('cricket_bowling_performances')
    op.drop_index(op.f('ix_cricket_batting_performances_id'), table_name='cricket_batting_performances')
    op.drop_table('cricket_batting_performances')
    op.drop_index(op.f('ix_cricket_innings_id'), table_name='cricket_innings')
    op.drop_table('cricket_innings')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index('ix_team_members_team_role', table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index('ix_team_members_status', table_name='team_members')
    op.drop_index(op.f('ix_team_members_role'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_team_invitations_team_id'), table_name='team_invitations')
    op.drop_index('ix_team_invitations_team_email', table_name='team_invitations')
    op.drop_index('ix_team_invitations_status_expires', table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_status'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_invited_user_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_invited_by_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_id'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_cricket_players_name'), table_name='cricket_players')
    op.drop_index(op.f('ix_cricket_players_id'), table_name='cricket_players')
    op.drop_table('cricket_players')
    op.drop_index(op.f('ix_cricket_matches_id'), table_name='cricket_matches')
    op.drop_table('cricket_matches')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_teams_team_type'), table_name='user_teams')
    op.drop_index(op.f('ix_user_teams_status'), table_name='user_teams')
    op.drop_index(op.f('ix_user_teams_name'), table_name='user_teams')
    op.drop_index(op.f('ix_user_teams_is_public'), table_name='user_teams')
    op.drop_index(op.f('ix_user_teams_id'), table_name='user_teams')
    op.drop_index(op.f('ix_user_teams_city'), table_name='user_teams')
    op.drop_index('ix_teams_name_type', table_name='user_teams')
    op.drop_index('ix_teams_location', table_name='user_teams')
    op.drop_table('user_teams')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_location'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_full_name'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_sport_profiles_user_id'), table_name='sport_profiles')
    op.drop_index(op.f('ix_sport_profiles_sport_type'), table_name='sport_profiles')
    op.drop_index(op.f('ix_sport_profiles_id'), table_name='sport_profiles')
    op.drop_table('sport_profiles')
    op.drop_index(op.f('ix_cricket_teams_name'), table_name='cricket_teams')
    op.drop_index(op.f('ix_cricket_teams_id'), table_name='cricket_teams')
    op.drop_table('cricket_teams')
    # ### end Alembic commands ###
