"""Add tournament tables with indexes

Revision ID: 87388052a1cf
Revises: 29c563fd012d
Create Date: 2025-09-19 00:03:08.899538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87388052a1cf'
down_revision: Union[str, None] = '29c563fd012d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tournament_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.Column('min_teams', sa.Integer(), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prize_money', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overs_per_innings', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('organizer_contact', sa.String(length=255), nullable=True),
    sa.Column('venue_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    op.create_index(op.f('ix_tournaments_start_date'), 'tournaments', ['start_date'], unique=False)
    op.create_index(op.f('ix_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.create_index(op.f('ix_tournaments_tournament_type'), 'tournaments', ['tournament_type'], unique=False)
    op.create_table('tournament_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('rule_value', sa.String(length=500), nullable=True),
    sa.Column('applies_to_stage', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_standings',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('matches_won', sa.Integer(), nullable=True),
    sa.Column('matches_lost', sa.Integer(), nullable=True),
    sa.Column('matches_tied', sa.Integer(), nullable=True),
    sa.Column('matches_no_result', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('runs_conceded', sa.Integer(), nullable=True),
    sa.Column('overs_faced', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('overs_bowled', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('net_run_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('previous_position', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'team_id')
    )
    op.create_table('tournament_teams',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('registered_by_id', sa.UUID(), nullable=False),
    sa.Column('registration_fee_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('seed_number', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'team_id')
    )
    op.create_table('tournament_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('is_knockout', sa.Boolean(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['cricket_matches.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'match_id', name='_tournament_match_uc')
    )
    op.create_index(op.f('ix_tournament_matches_round_number'), 'tournament_matches', ['round_number'], unique=False)
    op.create_index(op.f('ix_tournament_matches_stage'), 'tournament_matches', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_matches_stage'), table_name='tournament_matches')
    op.drop_index(op.f('ix_tournament_matches_round_number'), table_name='tournament_matches')
    op.drop_table('tournament_matches')
    op.drop_table('tournament_teams')
    op.drop_table('tournament_standings')
    op.drop_table('tournament_rules')
    op.drop_index(op.f('ix_tournaments_tournament_type'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_status'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_start_date'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
