"""Add statistics and analytics models

Revision ID: 9088662518cb
Revises: 87388052a1cf
Create Date: 2025-09-19 08:21:45.257701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9088662518cb'
down_revision: Union[str, None] = '87388052a1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('matches_qualification', sa.Integer(), nullable=True),
    sa.Column('last_match_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leaderboard_category_scope', 'leaderboards', ['category', 'scope', 'position'], unique=False)
    op.create_index('idx_leaderboard_scope_ranking', 'leaderboards', ['scope', 'scope_id', 'position'], unique=False)
    op.create_index('idx_leaderboard_user_category', 'leaderboards', ['user_id', 'category'], unique=False)
    op.create_table('player_career_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('innings_batted', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.Column('balls_faced', sa.Integer(), nullable=True),
    sa.Column('fours_hit', sa.Integer(), nullable=True),
    sa.Column('sixes_hit', sa.Integer(), nullable=True),
    sa.Column('times_out', sa.Integer(), nullable=True),
    sa.Column('times_not_out', sa.Integer(), nullable=True),
    sa.Column('innings_bowled', sa.Integer(), nullable=True),
    sa.Column('overs_bowled', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('runs_conceded', sa.Integer(), nullable=True),
    sa.Column('wickets_taken', sa.Integer(), nullable=True),
    sa.Column('best_bowling_figures', sa.String(length=10), nullable=True),
    sa.Column('maidens_bowled', sa.Integer(), nullable=True),
    sa.Column('catches_taken', sa.Integer(), nullable=True),
    sa.Column('stumpings_made', sa.Integer(), nullable=True),
    sa.Column('run_outs_effected', sa.Integer(), nullable=True),
    sa.Column('batting_average', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('batting_strike_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bowling_average', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bowling_strike_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bowling_economy_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tournaments_played', sa.Integer(), nullable=True),
    sa.Column('tournament_wins', sa.Integer(), nullable=True),
    sa.Column('man_of_match_awards', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_career_stats_batting_avg', 'player_career_stats', ['batting_average'], unique=False)
    op.create_index('idx_career_stats_bowling_avg', 'player_career_stats', ['bowling_average'], unique=False)
    op.create_index('idx_career_stats_runs', 'player_career_stats', ['runs_scored'], unique=False)
    op.create_index('idx_career_stats_wickets', 'player_career_stats', ['wickets_taken'], unique=False)
    op.create_table('player_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player1_id', sa.UUID(), nullable=False),
    sa.Column('player2_id', sa.UUID(), nullable=False),
    sa.Column('comparison_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('player1_wins', sa.Integer(), nullable=True),
    sa.Column('player2_wins', sa.Integer(), nullable=True),
    sa.Column('matches_together', sa.Integer(), nullable=True),
    sa.Column('player1_avg_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('player2_avg_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('player1_avg_wickets', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('player2_avg_wickets', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('dominance_factor', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('performance_gap', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comparison_players', 'player_comparisons', ['player1_id', 'player2_id'], unique=False)
    op.create_index('idx_comparison_type_scope', 'player_comparisons', ['comparison_type', 'scope_id'], unique=False)
    op.create_table('player_performance_trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('wickets_taken', sa.Integer(), nullable=True),
    sa.Column('batting_average', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bowling_average', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('strike_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('form_rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('consistency_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('improvement_factor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('centuries_scored', sa.Integer(), nullable=True),
    sa.Column('half_centuries_scored', sa.Integer(), nullable=True),
    sa.Column('five_wicket_hauls', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trends_form_rating', 'player_performance_trends', ['form_rating', 'period_end'], unique=False)
    op.create_index('idx_trends_user_period', 'player_performance_trends', ['user_id', 'period_type', 'period_start'], unique=False)
    op.create_table('team_season_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('matches_won', sa.Integer(), nullable=True),
    sa.Column('matches_lost', sa.Integer(), nullable=True),
    sa.Column('matches_tied', sa.Integer(), nullable=True),
    sa.Column('matches_no_result', sa.Integer(), nullable=True),
    sa.Column('total_runs_scored', sa.Integer(), nullable=True),
    sa.Column('total_balls_faced', sa.Integer(), nullable=True),
    sa.Column('highest_team_score', sa.Integer(), nullable=True),
    sa.Column('lowest_team_score', sa.Integer(), nullable=True),
    sa.Column('total_fours_hit', sa.Integer(), nullable=True),
    sa.Column('total_sixes_hit', sa.Integer(), nullable=True),
    sa.Column('total_runs_conceded', sa.Integer(), nullable=True),
    sa.Column('total_overs_bowled', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('total_wickets_taken', sa.Integer(), nullable=True),
    sa.Column('best_bowling_figures', sa.String(length=10), nullable=True),
    sa.Column('total_maidens', sa.Integer(), nullable=True),
    sa.Column('total_catches', sa.Integer(), nullable=True),
    sa.Column('total_stumpings', sa.Integer(), nullable=True),
    sa.Column('total_run_outs', sa.Integer(), nullable=True),
    sa.Column('team_batting_average', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('team_bowling_average', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('team_strike_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('team_economy_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('win_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tournament_position', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_performance_ranking', 'team_season_stats', ['season_year', 'win_percentage'], unique=False)
    op.create_index('idx_team_season_lookup', 'team_season_stats', ['team_id', 'season_year'], unique=False)
    op.create_index('idx_team_tournament_stats', 'team_season_stats', ['tournament_id', 'win_percentage'], unique=False)
    op.create_table('player_match_performances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('batted', sa.Boolean(), nullable=True),
    sa.Column('batting_position', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('balls_faced', sa.Integer(), nullable=True),
    sa.Column('fours_hit', sa.Integer(), nullable=True),
    sa.Column('sixes_hit', sa.Integer(), nullable=True),
    sa.Column('dismissal_type', sa.String(length=50), nullable=True),
    sa.Column('dismissed_by_player_id', sa.UUID(), nullable=True),
    sa.Column('bowled', sa.Boolean(), nullable=True),
    sa.Column('overs_bowled', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('runs_conceded', sa.Integer(), nullable=True),
    sa.Column('wickets_taken', sa.Integer(), nullable=True),
    sa.Column('maidens_bowled', sa.Integer(), nullable=True),
    sa.Column('wides_bowled', sa.Integer(), nullable=True),
    sa.Column('no_balls_bowled', sa.Integer(), nullable=True),
    sa.Column('catches_taken', sa.Integer(), nullable=True),
    sa.Column('stumpings_made', sa.Integer(), nullable=True),
    sa.Column('run_outs_effected', sa.Integer(), nullable=True),
    sa.Column('batting_points', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bowling_points', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fielding_points', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('man_of_match', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dismissed_by_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['cricket_matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_performance_ratings', 'player_match_performances', ['overall_rating', 'match_date'], unique=False)
    op.create_index('idx_performance_tournament', 'player_match_performances', ['tournament_id', 'match_date'], unique=False)
    op.create_index('idx_performance_user_date', 'player_match_performances', ['user_id', 'match_date'], unique=False)
    op.create_index('idx_performance_user_match', 'player_match_performances', ['user_id', 'match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_performance_user_match', table_name='player_match_performances')
    op.drop_index('idx_performance_user_date', table_name='player_match_performances')
    op.drop_index('idx_performance_tournament', table_name='player_match_performances')
    op.drop_index('idx_performance_ratings', table_name='player_match_performances')
    op.drop_table('player_match_performances')
    op.drop_index('idx_team_tournament_stats', table_name='team_season_stats')
    op.drop_index('idx_team_season_lookup', table_name='team_season_stats')
    op.drop_index('idx_team_performance_ranking', table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_index('idx_trends_user_period', table_name='player_performance_trends')
    op.drop_index('idx_trends_form_rating', table_name='player_performance_trends')
    op.drop_table('player_performance_trends')
    op.drop_index('idx_comparison_type_scope', table_name='player_comparisons')
    op.drop_index('idx_comparison_players', table_name='player_comparisons')
    op.drop_table('player_comparisons')
    op.drop_index('idx_career_stats_wickets', table_name='player_career_stats')
    op.drop_index('idx_career_stats_runs', table_name='player_career_stats')
    op.drop_index('idx_career_stats_bowling_avg', table_name='player_career_stats')
    op.drop_index('idx_career_stats_batting_avg', table_name='player_career_stats')
    op.drop_table('player_career_stats')
    op.drop_index('idx_leaderboard_user_category', table_name='leaderboards')
    op.drop_index('idx_leaderboard_scope_ranking', table_name='leaderboards')
    op.drop_index('idx_leaderboard_category_scope', table_name='leaderboards')
    op.drop_table('leaderboards')
    # ### end Alembic commands ###
