"""Add notification system models

Revision ID: f5f9f54f8d29
Revises: 9088662518cb
Create Date: 2025-09-19 10:08:42.457858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f9f54f8d29'
down_revision: Union[str, None] = '9088662518cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type_id', sa.UUID(), nullable=False),
    sa.Column('enabled_in_app', sa.Boolean(), nullable=False),
    sa.Column('enabled_email', sa.Boolean(), nullable=False),
    sa.Column('enabled_push', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('last_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('email_subject_template', sa.String(length=200), nullable=True),
    sa.Column('email_body_template', sa.Text(), nullable=True),
    sa.Column('push_title_template', sa.String(length=100), nullable=True),
    sa.Column('push_body_template', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('os_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_index('idx_device_tokens_platform', 'user_device_tokens', ['platform', 'is_active'], unique=False)
    op.create_index('idx_device_tokens_user', 'user_device_tokens', ['user_id', 'is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('related_match_id', sa.UUID(), nullable=True),
    sa.Column('related_team_id', sa.UUID(), nullable=True),
    sa.Column('related_tournament_id', sa.UUID(), nullable=True),
    sa.Column('related_user_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_in_app', sa.Boolean(), nullable=False),
    sa.Column('sent_email', sa.Boolean(), nullable=False),
    sa.Column('sent_push', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
    sa.ForeignKeyConstraint(['related_match_id'], ['cricket_matches.id'], ),
    sa.ForeignKeyConstraint(['related_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['related_tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_expires', 'notifications', ['expires_at'], unique=False)
    op.create_index('idx_notifications_scheduled', 'notifications', ['scheduled_for'], unique=False)
    op.create_index('idx_notifications_type_created', 'notifications', ['notification_type_id', 'created_at'], unique=False)
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_logs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_queue_channel_status', 'notification_queue', ['channel', 'status'], unique=False)
    op.create_index('idx_queue_retry', 'notification_queue', ['next_retry', 'retry_count'], unique=False)
    op.create_index('idx_queue_status_priority', 'notification_queue', ['status', 'priority', 'scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_queue_status_priority', table_name='notification_queue')
    op.drop_index('idx_queue_retry', table_name='notification_queue')
    op.drop_index('idx_queue_channel_status', table_name='notification_queue')
    op.drop_table('notification_queue')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_index('idx_notifications_type_created', table_name='notifications')
    op.drop_index('idx_notifications_scheduled', table_name='notifications')
    op.drop_index('idx_notifications_expires', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_device_tokens_user', table_name='user_device_tokens')
    op.drop_index('idx_device_tokens_platform', table_name='user_device_tokens')
    op.drop_table('user_device_tokens')
    op.drop_table('notification_templates')
    op.drop_table('notification_preferences')
    op.drop_table('notification_types')
    # ### end Alembic commands ###
